/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WorldRouteImport } from './routes/world'
import { Route as SportsRouteImport } from './routes/sports'
import { Route as McpRouteImport } from './routes/mcp'
import { Route as FeedbackRouteImport } from './routes/feedback'
import { Route as FeedRouteImport } from './routes/feed'
import { Route as ExploreRouteImport } from './routes/explore'
import { Route as BotRouteImport } from './routes/bot'
import { Route as BookmarksRouteImport } from './routes/bookmarks'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as IndexRouteImport } from './routes/index'
import { Route as StateCodeRouteImport } from './routes/state.$code'
import { Route as ArticleIdRouteImport } from './routes/article.$id'
import { Route as ApiChatRouteImport } from './routes/api/chat'
import { Route as AdminRolesRouteImport } from './routes/admin.roles'
import { Route as Char91DotwellKnownChar93OauthProtectedResourceRouteImport } from './routes/[.well-known]/oauth-protected-resource'
import { Route as Char91DotmcpChar93ListToolsRouteImport } from './routes/[.mcp]/list-tools'
import { Route as Char91DotmcpChar93InvokeToolToolRouteImport } from './routes/[.mcp]/invoke-tool/$tool'

const WorldRoute = WorldRouteImport.update({
  id: '/world',
  path: '/world',
  getParentRoute: () => rootRouteImport,
} as any)
const SportsRoute = SportsRouteImport.update({
  id: '/sports',
  path: '/sports',
  getParentRoute: () => rootRouteImport,
} as any)
const McpRoute = McpRouteImport.update({
  id: '/mcp',
  path: '/mcp',
  getParentRoute: () => rootRouteImport,
} as any)
const FeedbackRoute = FeedbackRouteImport.update({
  id: '/feedback',
  path: '/feedback',
  getParentRoute: () => rootRouteImport,
} as any)
const FeedRoute = FeedRouteImport.update({
  id: '/feed',
  path: '/feed',
  getParentRoute: () => rootRouteImport,
} as any)
const ExploreRoute = ExploreRouteImport.update({
  id: '/explore',
  path: '/explore',
  getParentRoute: () => rootRouteImport,
} as any)
const BotRoute = BotRouteImport.update({
  id: '/bot',
  path: '/bot',
  getParentRoute: () => rootRouteImport,
} as any)
const BookmarksRoute = BookmarksRouteImport.update({
  id: '/bookmarks',
  path: '/bookmarks',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const StateCodeRoute = StateCodeRouteImport.update({
  id: '/state/$code',
  path: '/state/$code',
  getParentRoute: () => rootRouteImport,
} as any)
const ArticleIdRoute = ArticleIdRouteImport.update({
  id: '/article/$id',
  path: '/article/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRolesRoute = AdminRolesRouteImport.update({
  id: '/admin/roles',
  path: '/admin/roles',
  getParentRoute: () => rootRouteImport,
} as any)
const Char91DotwellKnownChar93OauthProtectedResourceRoute =
  Char91DotwellKnownChar93OauthProtectedResourceRouteImport.update({
    id: '/.well-known/oauth-protected-resource',
    path: '/.well-known/oauth-protected-resource',
    getParentRoute: () => rootRouteImport,
  } as any)
const Char91DotmcpChar93ListToolsRoute =
  Char91DotmcpChar93ListToolsRouteImport.update({
    id: '/.mcp/list-tools',
    path: '/.mcp/list-tools',
    getParentRoute: () => rootRouteImport,
  } as any)
const Char91DotmcpChar93InvokeToolToolRoute =
  Char91DotmcpChar93InvokeToolToolRouteImport.update({
    id: '/.mcp/invoke-tool/$tool',
    path: '/.mcp/invoke-tool/$tool',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/bookmarks': typeof BookmarksRoute
  '/bot': typeof BotRoute
  '/explore': typeof ExploreRoute
  '/feed': typeof FeedRoute
  '/feedback': typeof FeedbackRoute
  '/mcp': typeof McpRoute
  '/sports': typeof SportsRoute
  '/world': typeof WorldRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/admin/roles': typeof AdminRolesRoute
  '/api/chat': typeof ApiChatRoute
  '/article/$id': typeof ArticleIdRoute
  '/state/$code': typeof StateCodeRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/bookmarks': typeof BookmarksRoute
  '/bot': typeof BotRoute
  '/explore': typeof ExploreRoute
  '/feed': typeof FeedRoute
  '/feedback': typeof FeedbackRoute
  '/mcp': typeof McpRoute
  '/sports': typeof SportsRoute
  '/world': typeof WorldRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/admin/roles': typeof AdminRolesRoute
  '/api/chat': typeof ApiChatRoute
  '/article/$id': typeof ArticleIdRoute
  '/state/$code': typeof StateCodeRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/bookmarks': typeof BookmarksRoute
  '/bot': typeof BotRoute
  '/explore': typeof ExploreRoute
  '/feed': typeof FeedRoute
  '/feedback': typeof FeedbackRoute
  '/mcp': typeof McpRoute
  '/sports': typeof SportsRoute
  '/world': typeof WorldRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/admin/roles': typeof AdminRolesRoute
  '/api/chat': typeof ApiChatRoute
  '/article/$id': typeof ArticleIdRoute
  '/state/$code': typeof StateCodeRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/bookmarks'
    | '/bot'
    | '/explore'
    | '/feed'
    | '/feedback'
    | '/mcp'
    | '/sports'
    | '/world'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/admin/roles'
    | '/api/chat'
    | '/article/$id'
    | '/state/$code'
    | '/.mcp/invoke-tool/$tool'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/bookmarks'
    | '/bot'
    | '/explore'
    | '/feed'
    | '/feedback'
    | '/mcp'
    | '/sports'
    | '/world'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/admin/roles'
    | '/api/chat'
    | '/article/$id'
    | '/state/$code'
    | '/.mcp/invoke-tool/$tool'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/bookmarks'
    | '/bot'
    | '/explore'
    | '/feed'
    | '/feedback'
    | '/mcp'
    | '/sports'
    | '/world'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/admin/roles'
    | '/api/chat'
    | '/article/$id'
    | '/state/$code'
    | '/.mcp/invoke-tool/$tool'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  BookmarksRoute: typeof BookmarksRoute
  BotRoute: typeof BotRoute
  ExploreRoute: typeof ExploreRoute
  FeedRoute: typeof FeedRoute
  FeedbackRoute: typeof FeedbackRoute
  McpRoute: typeof McpRoute
  SportsRoute: typeof SportsRoute
  WorldRoute: typeof WorldRoute
  Char91DotmcpChar93ListToolsRoute: typeof Char91DotmcpChar93ListToolsRoute
  Char91DotwellKnownChar93OauthProtectedResourceRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  AdminRolesRoute: typeof AdminRolesRoute
  ApiChatRoute: typeof ApiChatRoute
  ArticleIdRoute: typeof ArticleIdRoute
  StateCodeRoute: typeof StateCodeRoute
  Char91DotmcpChar93InvokeToolToolRoute: typeof Char91DotmcpChar93InvokeToolToolRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/world': {
      id: '/world'
      path: '/world'
      fullPath: '/world'
      preLoaderRoute: typeof WorldRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sports': {
      id: '/sports'
      path: '/sports'
      fullPath: '/sports'
      preLoaderRoute: typeof SportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mcp': {
      id: '/mcp'
      path: '/mcp'
      fullPath: '/mcp'
      preLoaderRoute: typeof McpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/feedback': {
      id: '/feedback'
      path: '/feedback'
      fullPath: '/feedback'
      preLoaderRoute: typeof FeedbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/feed': {
      id: '/feed'
      path: '/feed'
      fullPath: '/feed'
      preLoaderRoute: typeof FeedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/explore': {
      id: '/explore'
      path: '/explore'
      fullPath: '/explore'
      preLoaderRoute: typeof ExploreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bot': {
      id: '/bot'
      path: '/bot'
      fullPath: '/bot'
      preLoaderRoute: typeof BotRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bookmarks': {
      id: '/bookmarks'
      path: '/bookmarks'
      fullPath: '/bookmarks'
      preLoaderRoute: typeof BookmarksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/state/$code': {
      id: '/state/$code'
      path: '/state/$code'
      fullPath: '/state/$code'
      preLoaderRoute: typeof StateCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/article/$id': {
      id: '/article/$id'
      path: '/article/$id'
      fullPath: '/article/$id'
      preLoaderRoute: typeof ArticleIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/roles': {
      id: '/admin/roles'
      path: '/admin/roles'
      fullPath: '/admin/roles'
      preLoaderRoute: typeof AdminRolesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.well-known/oauth-protected-resource': {
      id: '/.well-known/oauth-protected-resource'
      path: '/.well-known/oauth-protected-resource'
      fullPath: '/.well-known/oauth-protected-resource'
      preLoaderRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.mcp/list-tools': {
      id: '/.mcp/list-tools'
      path: '/.mcp/list-tools'
      fullPath: '/.mcp/list-tools'
      preLoaderRoute: typeof Char91DotmcpChar93ListToolsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.mcp/invoke-tool/$tool': {
      id: '/.mcp/invoke-tool/$tool'
      path: '/.mcp/invoke-tool/$tool'
      fullPath: '/.mcp/invoke-tool/$tool'
      preLoaderRoute: typeof Char91DotmcpChar93InvokeToolToolRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  BookmarksRoute: BookmarksRoute,
  BotRoute: BotRoute,
  ExploreRoute: ExploreRoute,
  FeedRoute: FeedRoute,
  FeedbackRoute: FeedbackRoute,
  McpRoute: McpRoute,
  SportsRoute: SportsRoute,
  WorldRoute: WorldRoute,
  Char91DotmcpChar93ListToolsRoute: Char91DotmcpChar93ListToolsRoute,
  Char91DotwellKnownChar93OauthProtectedResourceRoute:
    Char91DotwellKnownChar93OauthProtectedResourceRoute,
  AdminRolesRoute: AdminRolesRoute,
  ApiChatRoute: ApiChatRoute,
  ArticleIdRoute: ArticleIdRoute,
  StateCodeRoute: StateCodeRoute,
  Char91DotmcpChar93InvokeToolToolRoute: Char91DotmcpChar93InvokeToolToolRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
